# Generated by Django 5.0 on 2024-11-12 20:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('mortgage', models.IntegerField(default=0)),
                ('current_rent', models.IntegerField(default=0)),
                ('market_rent', models.IntegerField(default=0)),
                ('photo', models.ImageField(default='', upload_to='images/')),
                ('city', models.CharField(choices=[('liverpool', 'Liverpool'), ('manchester', 'Manchester'), ('london', 'London')], default='', max_length=200)),
                ('mortgage_deal_expiry_date', models.DateField(default=datetime.date.today)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
    ]
